### ISSUE TITLE
No signature of method: java.util.ArrayList.replaceAll()

### ISSUE THREAD

**Issue by tdespenza** [theaspect/HelloWorld#1]
Grails: 2.4.5
Groovy: 2.4.8
Java: 1.8.0_66
OS: Mac

Getting this error when specifying datatables as a required dependency.
```
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <asset:javascript>: No signature of method: java.util.ArrayList.replaceAll() is applicable for argument types: (java.lang.String, java.lang.String) values: [\./, ]
Possible solutions: replaceAll(java.util.function.UnaryOperator)
	at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.createGroovyPageException(GroovyPageView.java:127)
	at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.handleException(GroovyPageView.java:104)
	at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:75)
	at org.codehaus.groovy.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:49)
	at org.codehaus.groovy.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:33)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:267)
	at org.codehaus.groovy.grails.web.sitemesh.SpringMVCViewDecorator.render(SpringMVCViewDecorator.java:69)
	... 101 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <asset:javascript>: No signature of method: java.util.ArrayList.replaceAll() is applicable for argument types: (java.lang.String, java.lang.String) values: [\./, ]
Possible solutions: replaceAll(java.util.function.UnaryOperator)
	at org.codehaus.groovy.grails.web.pages.GroovyPage.throwRootCause(GroovyPage.java:527)
	at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:470)
	at sun.reflect.GeneratedMethodAccessor855.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1110)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at Users_tdespenza_Projects_esco_docreg_grails_app_views_layouts_main_gsp$_run_closure1.doCall(main.gsp:15)
	at sun.reflect.GeneratedMethodAccessor1069.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.executeClosure(GroovyPageTagBody.java:206)
	at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.captureClosureOutput(GroovyPageTagBody.java:108)
	at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.call(GroovyPageTagBody.java:219)
	at org.codehaus.groovy.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy:49)
	at org.codehaus.groovy.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy)
	at org.codehaus.groovy.grails.plugins.web.taglib.SitemeshTagLib$_closure1.doCall(SitemeshTagLib.groovy:125)
	at sun.reflect.GeneratedMethodAccessor763.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTagLibClosure(GroovyPage.java:501)
	at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:419)
	at org.codehaus.groovy.grails.web.pages.GroovyPage$invokeTag$12.callCurrent(Unknown Source)
	at Users_tdespenza_Projects_esco_docreg_grails_app_views_layouts_main_gsp.run(main.gsp:16)
	at org.codehaus.groovy.grails.web.pages.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:217)
	at org.codehaus.groovy.grails.web.pages.GroovyPageWritable.writeTo(GroovyPageWritable.java:128)
	at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:71)
	... 105 more
Caused by: groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.replaceAll() is applicable for argument types: (java.lang.String, java.lang.String) values: [\./, ]
Possible solutions: replaceAll(java.util.function.UnaryOperator)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at asset.pipeline.bower.BowerDownloadService.getLibraryName(BowerDownloadService.groovy:114)
	at asset.pipeline.bower.BowerDownloadService$getLibraryName$3.callCurrent(Unknown Source)
	at asset.pipeline.bower.BowerDownloadService.getLibrary(BowerDownloadService.groovy:33)
	at asset.pipeline.bower.BowerDownloadService$getLibrary.call(Unknown Source)
	at asset.pipeline.bower.BowerAssetResolver$_getAsset_closure1.doCall(BowerAssetResolver.groovy:30)
	at asset.pipeline.bower.BowerAssetResolver$_getAsset_closure1.doCall(BowerAssetResolver.groovy)
	at sun.reflect.GeneratedMethodAccessor1045.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:166)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:572)
	at asset.pipeline.AbstractAssetFile.getInputStream(AbstractAssetFile.groovy:72)
	at asset.pipeline.bower.BowerAssetFile.getInputStream(BowerAssetFile.groovy)
	at asset.pipeline.DirectiveProcessor.findDirectives(DirectiveProcessor.groovy:155)
	at asset.pipeline.DirectiveProcessor.getDependencyTree(DirectiveProcessor.groovy:141)
	at sun.reflect.GeneratedMethodAccessor969.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at asset.pipeline.DirectiveProcessor.requireFileDirective(DirectiveProcessor.groovy:273)
	at sun.reflect.GeneratedMethodAccessor1018.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:80)
	at asset.pipeline.DirectiveProcessor.callDirective(DirectiveProcessor.groovy:192)
	at asset.pipeline.DirectiveProcessor.findDirectives(DirectiveProcessor.groovy:171)
	at asset.pipeline.DirectiveProcessor.getDependencyTree(DirectiveProcessor.groovy:141)
	at sun.reflect.GeneratedMethodAccessor969.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at asset.pipeline.DirectiveProcessor.getFlattenedRequireList(DirectiveProcessor.groovy:81)
	at asset.pipeline.DirectiveProcessor$getFlattenedRequireList.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at asset.pipeline.DirectiveProcessor$getFlattenedRequireList.call(Unknown Source)
	at asset.pipeline.AssetPipeline.getDependencyList(AssetPipeline.groovy:83)
	at asset.pipeline.AssetPipeline$getDependencyList$0.call(Unknown Source)
	at asset.pipeline.grails.AssetsTagLib.element(AssetsTagLib.groovy:81)
	at asset.pipeline.grails.AssetsTagLib.this$2$element(AssetsTagLib.groovy)
	at sun.reflect.GeneratedMethodAccessor966.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1151)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at asset.pipeline.grails.AssetsTagLib$_closure1.doCall(AssetsTagLib.groovy:27)
	at sun.reflect.GeneratedMethodAccessor1013.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at asset.pipeline.grails.AssetsTagLib$_closure1.call(AssetsTagLib.groovy)
	at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTagLibClosure(GroovyPage.java:494)
	at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:419)
	... 153 more
```

In line 115 of the BowerDownloadService, this is the text response

```
{
	"name": "datatables",
	"main": [
		"media/js/jquery.dataTables.js",
		"media/css/jquery.dataTables.css",
		"media/images/sort_asc.png",
		"media/images/sort_asc_disabled.png",
		"media/images/sort_both.png",
		"media/images/sort_desc.png",
		"media/images/sort_desc_disabled.png"
	],
	"dependencies": {
		"jquery": ">=1.7.0"
	},
	"license": "MIT",
	"keywords": [
		"jquery",
		"datatables",
		"table",
		"javascript",
		"library"
	],
	"ignore": [
		"/.*",
		"examples",
		"media/unit_testing",
		"composer.json",
		"dataTables.jquery.json",
		"package.json"
	]
}
```

main is an array that is converted to an array list instead of a string literal shown here

`String fileName = parseData.main.replaceAll("\\./", "")`

So it tries to do a replace all on the array list causing the error.

**Comment by theaspect** [comment]
It wasn't designed for multiple files, but I'll look what I can do

**Comment by tdespenza** [comment]
_Thanks._

**Comment by theaspect** [comment]
@tdespenza i fixed issue, but you can only download first js file. Need complex rewrite #2
Try version 0.3
